path: ''
train: train_list.txt
val: val_list.txt
nc: 37
names:
- BEN_signal_symbol
- BEN_chip
- BEN_special_sign
- residence_place
- height
- BEN_eyes
- emergency_contact
- BEN_complexion
- BEN_hair
- issue_date
- signature
- expiry_date
- barcode
- BEN_qr_code
- BEN_sun
- BEN_special_symbol
- BEN_consulat_mail
- lieu_residence
- BEN_birth_info
- flag
- national_logo
- BEN_title_republic
- title_carte
- BEN_title_consulat
- document_number
- holder_photo
- BEN_bandwidth
- last_name
- first_names
- father_fullname
- mother_fullname
- BEN_coconut_tree
- BEN_country_map
- profession
- small_photo
- nom
- prenoms
